name: Publish yggdrasil-go-docker to Docker HUB
on:
  schedule:
    - cron: '0 0 8-14,22-28 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone yggdrasil-go
        run: |
            git clone https://github.com/MakishimuAkuma/yggdrasil-go-docker.git .
            git clone https://github.com/yggdrasil-network/yggdrasil-go.git
            echo "version=$(git -C ./yggdrasil-go describe --tags --abbrev=0)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ env.version }}, ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          
